import { Trophy } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { Page } from "../components/UI";
import { tournaments } from "../data/platform";
import { InfoPanel } from "./shared";

export function TournamentDetailPage() {
  const params = useParams();
  const item = tournaments.find((t) => t.slug === params.slug) ?? tournaments[0];

  return (
    <Page>
      <section className="detail-hero">
        <div className={`detail-visual visual-${item.accent}`}>
          <Trophy size={44} />
          <strong>{item.sport}</strong>
          <span>{item.teams}/{item.capacity} teams</span>
        </div>
        <div>
          <span className={`status ${item.accent}`}>{item.status}</span>
          <h1>{item.name}</h1>
          <p>{item.sport} tournament in {item.location}. Registration, payment, rules, schedule, venue, teams, and live updates are all connected in the final frontend structure.</p>
          <Link className="btn btn-primary" to={`/tournaments/${item.slug}/register`}>Register now</Link>
        </div>
      </section>
      <div className="detail-grid">
        <InfoPanel title="Tournament Rules" items={["Roster min/max validation", "Document verification required", "Fixture and bracket generated by tournament engine", "Payment required before approval"]} to="/faq" />
        <InfoPanel title="Prize Pool" items={[item.prize, "Winner trophy", "MVP award", "Digital certificates"]} to="/leaderboards" highlight />
        <InfoPanel title="Schedule" items={["Qualifiers - Aug 14", "Quarter Finals - Aug 20", "Semi Finals - Aug 26", "Final - Sep 02"]} to="/live" />
        <InfoPanel title="Venue" items={[item.location, "Smart venue map", "Officials and support desk", "Emergency contacts"]} to="/contact" />
      </div>
    </Page>
  );
}
